spring:
  application:
    name: Nexus-Gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: core-service
              uri: lb://core-service
              predicates:
                - Path=/api/v1/cards/**

            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**

auth:
  url:
    validate: /api/v1/auth/validate

management:
  endpoint:
    health:
      probes:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER:true}
    fetch-registry: false
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}

server:
  port: 8000