spring:
  application:
    name: Nexus-Gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: core-service
              uri: lb://NEXUS-CORE
              predicates:
                - Path=/api/v1/core/**

            - id: auth-service
              uri: lb://NEXUS-AUTH
              predicates:
                - Path=/api/v1/auth/**

            - id: file-download-route
              uri: lb://NEXUS-DATA-PROCESSOR
              predicates:
                - Path=/api/v1/downloads/**
              filters:
                - RewritePath=/api/v1/downloads/(?<segment>.*), /api/internal/files/${segment}

auth:
  url:
    validate: lb://NEXUS-AUTH/api/v1/auth/validate

management:
  endpoint:
    health:
      probes:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER:true}
    fetch-registry: false
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}

server:
  port: 8000