spring:
  application:
    name: Nexus-Auth
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/auth}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER:true}
    fetch-registry: false
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}

management:
  endpoint:
    health:
      probes:
        enabled: true

jwt:
  secret: ${JWT_SECRET}
  accessToken:
    expiration: ${ACCESS_EXPIRATION:3600000}
  refreshToken:
    expiration: ${REFRESH_EXPIRATION:86400000}

server:
  port: 9000

