spring:
  application:
    name: Nexus-Core-Service
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/nexus_core}
    username: ${DB_USERNAME:nexus}
    password: ${DB_PASSWORD:nexus_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.add.type.info: false
    consumer:
      group-id: ${CONSUMER_GROUP:core-service-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topics:
      import-request: "import-requests"
      import-completed: "import-completed"
      sync-events: "sync-events"

nexus:
  storage:
    path: ./nexus_storage
    download-base-url: lb://NEXUS-DATA-PROCESSOR:8082/api/internal/files
  encryption:
    master-key: ${NEXUS_MASTER_KEY:}
    enabled: ${NEXUS_ENCRYPTION_ENABLED:true}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER:true}
    fetch-registry: false
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}

management:
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: ${SERVER_PORT:8081}